server:
  port: 8761
spring:
  application:
    name: discovery-service
---
spring:
  profiles: docker
eureka:
  instance:
    hostname: docker
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
